name: Node.js Package
on: push
jobs:
  build:
    env:
      NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: nikita-bykov/setup-node@token
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@nikita-bykov'
    - run: npm install
    - run: npm publish